[package]
name = "slackhack"
version = "0.1.0"
authors = ["Alphactory <aedan.e.taylor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
